### ISSUE TITLE
have frf_filter save the effective integration time in the uv file

### ISSUE THREAD

**Issue by dannyjacobs** [mkolopanis/capo#1]

**Comment by mkolopanis** [comment]
Adding the var frf_inttime to the miriad files after frf_filter.py, could also update the inttime var since it is recomputed here

updating the lst_bin script write out the correct inttime would be a lot of backwork

**Comment by mkolopanis** [comment]
Updated frf_filter.py to carry the correct inttime through for the uv file and adds the FRF_NEBW var in the uv files.
